navikt/fp-frontend

packages/fakta-uttak/src/components/UttakNyPeriode.tsx
Overstyring av fakta uttak har gitt JsonMappingFeil i loggene . ArbeidsgiverLagreDto tar "identifikator" og "aktørId" og orgnr er satt i aktørid (tilsvarende vil skje for private). Sjekker på om er virksomhet i transform ...
```
Cannot construct instance of `no.nav.foreldrepenger.domene.typer.AktørId`, problem: Ugyldig aktørId '973149229', tillatt pattern: ^\d{13}$  
>no.nav.foreldrepenger.web.app.tjenester.behandling.uttak.dto.OverstyringFaktaUttakDto$OverstyrerFaktaUttakDto["bekreftedePerioder"]->java.util.ArrayList[1]->no.nav.foreldrepenger.web.app.tjenester.behandling.uttak.dto.BekreftetOppgittPeriodeDto["bekreftetPeriode"]->no.nav.foreldrepenger.web.app.tjenester.behandling.uttak.dto.KontrollerFaktaPeriodeLagreDto["arbeidsgiver"]->no.nav.foreldrepenger.web.app.tjenester.behandling.utt …
```
=> NOJIRA feil i overstyr fakta uttak

packages/behandling-klage/src/prosessPaneler/VurderingFellesProsessStegInitPanel.spec.tsx, packages/kodeverk/src/kodeverkTyper.ts, packages/prosess-klagevurdering/i18n/nb_NO.json, packages/prosess-klagevurdering/src/KlagevurderingProsessIndex.spec.tsx, packages/prosess-klagevurdering/src/KlagevurderingProsessIndex.stories.tsx, packages/prosess-klagevurdering/src/KlagevurderingProsessIndex.tsx, packages/prosess-klagevurdering/src/components/felles/TempsaveKlageButton.tsx, packages/prosess-klagevurdering/src/components/nfp/BehandleKlageFormNfp.tsx, packages/prosess-klagevurdering/src/components/nfp/KlageVurderingRadioOptionsNfp.tsx, packages/storybook-utils/mocks/alleKodeverk.json, packages/storybook/stories/mocks/alleKodeverk.json, packages/types-avklar-aksjonspunkter/src/prosess/KlageVurderingResultatAp.ts, packages/types/src/klageVurderingTsType.ts
Opplegg for at klagebehandler i NFP skal velge lovhjemmel som klagen gjelder. KA/NK skal ikke velge hjemmel
TotalDto kommer med list av aktuelle hjemler (gitt av sakstype) og Klagevurderingdto med en valgt hjemmel.
Har testet mellomlagring og bekreft lokalt. Gjerne feedback. Prodsetting 2022 januar
Det er noen mangler i KlageVedtak-panel  (viser ikke årsak til medhold) og for beslutter står det bare aktuell hjemmel uten "Hjemmel:" fulgt av valgt hjemmel.
=> TFP-4786 NFP Klagevurdering - skal velge hjemmel

packages/prosess-uttak/src/components/UttakActivity.tsx
Må sjekke på om erOppfylt for velge riktig kode. Håper det gjør reduserer avvikslogg backend.
Neste omgang: fjerne perioderesultatårsak fra all logikk og gå fra to til ett SelectField i UttakActivity dersom erOpptylt defined.
=> Manglet sjekk på perioderesultattype og fikk feil verdi

packages/sak-meny-henlegg/i18n/nb_NO.json, packages/sak-meny-henlegg/src/MenyHenleggIndex.spec.tsx, packages/sak-meny-henlegg/src/MenyHenleggIndex.stories.tsx, packages/sak-meny-henlegg/src/components/HenleggBehandlingModal.tsx, packages/storybook-utils/mocks/alleKodeverk.json
Fjerner henleggelsesårsaken fra menyen - ettersom det ligger en del backendlogikk for flytting.
Beholder i behandlingsResultatType.ts i tilfelle visningsbehov
=> TFP-4917 fjerne manglende beregningsregler som henleggelsesårsak

packages/papirsoknad-fp/i18n/nb_NO.json, packages/papirsoknad-fp/src/components/ForeldrepengerForm.tsx, packages/papirsoknad-fp/src/components/permisjon/PermisjonRettigheterPanel.spec.tsx, packages/papirsoknad-fp/src/components/permisjon/PermisjonRettigheterPanel.tsx, packages/papirsoknad-fp/src/components/permisjon/RenderPermisjonPeriodeFieldArray.tsx, packages/papirsoknad-panel-annen-forelder/i18n/nb_NO.json
Skal kunne registere om mor er uføretrygdet dersom bruker er far og mor ikke har rett.
Legger inn at mor har foreldrepenger EØS i samme slengen - den er ikke aktiv før 2/8-22
=> TFP-5011 papirsøknad registrere mor uføre og mor fp eøs

packages/prosess-uttak/src/UttakProsessIndex.stories.tsx, packages/prosess-uttak/src/components/Uttak.spec.tsx, packages/prosess-uttak/src/components/Uttak.tsx, packages/prosess-uttak/src/components/UttakActivity.spec.tsx, packages/prosess-uttak/src/components/UttakActivity.tsx, packages/prosess-uttak/src/components/UttakMedsokerReadOnly.tsx, packages/prosess-uttak/src/components/UttakTimeLineData.spec.tsx, packages/prosess-uttak/src/components/UttakTimeLineData.tsx, packages/types/src/uttaksresultatPeriodeTsType.ts
Sender opp ett nytt felt i uttak-resultatet "søkerErMor" + to nye felt i ArsakKodeverk - sortering og synligForRolle
Dette vil gi en bedre sortering enn dagens andre, femte, fjerde, første, sjette, sjuende, tredje
Dessuten langt færre årsaker å velge mellom for de fleste tilfellene.
Testet lokalt for både mor og far og ulike konti. Funker bra.
Tor ser kanskje mer elegante måter å gjøre dette på?
Notat: kreverSammenhengedeUttak finnes også i uttak-resultatet. Nå ser det ut som det hentes fra eget endepunkt.
=> TFP-2754 sortering og mer filtrering av uttak-årsaker

packages/behandling-fp/src/data/fpBehandlingApi.ts, packages/behandling-fp/src/prosessPaneler/UttakProsessStegInitPanel.spec.tsx, packages/behandling-fp/src/prosessPaneler/UttakProsessStegInitPanel.tsx, packages/prosess-uttak/src/UttakProsessIndex.spec.tsx, packages/prosess-uttak/src/UttakProsessIndex.stories.tsx, packages/prosess-uttak/src/UttakProsessIndex.tsx, packages/prosess-uttak/src/components/Uttak.spec.tsx, packages/prosess-uttak/src/components/Uttak.tsx, packages/prosess-uttak/src/components/UttakActivity.spec.tsx, packages/prosess-uttak/src/components/UttakActivity.tsx, packages/prosess-uttak/src/components/UttakMedsokerReadOnly.tsx, packages/prosess-uttak/src/components/UttakPanel.spec.tsx, packages/prosess-uttak/src/components/UttakPanel.tsx, packages/prosess-uttak/src/components/UttakTimeLineData.spec.tsx, packages/prosess-uttak/src/components/UttakTimeLineData.tsx, packages/types/src/uttaksresultatPeriodeTsType.ts
Bruker info om sammenhengende uttak, minsterett og mor fra ny filter-del i Dto.
Fjerner ref til ressurslenke for krever-sammenhengende-uttak
@tor-nav burde vi sende uttaksresultat lenger ned til der den egentlig trengs - dvs mapAarsaker i UttakActivity ?
=> Forenkle paramtere til filtrering + legge på utenMinsterett

packages/behandling-fp/src/data/fpBehandlingApi.ts, packages/behandling-fp/src/prosessPaneler/BeregningsgrunnlagProsessStegInitPanel.tsx, packages/behandling-fp/src/prosessPaneler/SoknadsfristProsessStegInitPanel.tsx, packages/behandling-fp/src/prosessPaneler/UttakProsessStegInitPanel.spec.tsx, packages/behandling-fp/src/prosessPaneler/UttakProsessStegInitPanel.tsx, packages/behandling-svp/src/data/svpBehandlingApi.ts, packages/behandling-svp/src/prosessPaneler/BeregningsgrunnlagProsessStegInitPanel.tsx, packages/behandling-svp/src/prosessPaneler/SoknadsfristProsessStegInitPanel.tsx, packages/prosess-soknadsfrist/src/VurderSoknadsfristForeldrepengerIndex.stories.tsx, packages/prosess-soknadsfrist/src/VurderSoknadsfristForeldrepengerIndex.tsx, packages/prosess-soknadsfrist/src/components/VurderSoknadsfristForeldrepengerForm.tsx, packages/prosess-tilkjent-ytelse/src/components/TilkjentYtelsePanel.tsx, packages/prosess-uttak/src/UttakProsessIndex.spec.tsx, packages/prosess-uttak/src/UttakProsessIndex.stories.tsx, packages/prosess-uttak/src/UttakProsessIndex.tsx, packages/prosess-uttak/src/components/Uttak.spec.tsx, packages/prosess-uttak/src/components/Uttak.tsx, packages/prosess-uttak/src/components/UttakPanel.spec.tsx, packages/prosess-uttak/src/components/UttakPanel.tsx, packages/prosess-vedtak/src/VedtakProsessIndex.stories.tsx, packages/prosess-vilkar-soknadsfrist/src/SoknadsfristVilkarProsessIndex.stories.tsx, packages/prosess-vilkar-soknadsfrist/src/SoknadsfristVilkarProsessIndex.tsx, packages/prosess-vilkar-soknadsfrist/src/components/ErSoknadsfristVilkaretOppfyltForm.tsx, packages/types/index.ts, packages/types/src/soknadTsType.ts, packages/types/src/uttakPeriodeGrenseTsType.tsx, packages/types/src/vilkarTsType.ts
Uttakperiodegrense er i praksis en overstyrt/gjeldende søknad.mottattDato
* Legger inn overstyrt søknadMottatt, perioder og frister i soknadTsType / søknadsfrist
* Standardiserer bruk av mottattdato i søknadsfristpanelene
* fjerner uttakPeriodeGrense
* Legger til overstyrt mottatt dato i tilkjent ytelse
=> TFP-5065 standardisere søknadsfrist i søknaddto

.deploy/dev-gcp-teamforeldrepenger.json
Alle kall mot `/fpfordel/api` blir sendt videre til fpfordel backend.
=> Legger inn proxy oppsett for kommunikasjon mellom frontend og backend.

packages/fakta-medlemskap/src/MedlemskapFaktaIndex.spec.tsx, packages/fakta-medlemskap/src/MedlemskapFaktaIndex.stories.tsx, packages/fakta-medlemskap/src/components/MedlemskapInfoPanel.tsx
Feltet "erAktivt" i aksjonspunkt er true både for åpne og utførte aksjonspunkt (og slik har det vært siden 2019 ...).
Når 5019 (vanlig medlemskap) er utført og 5053 (løpende) er åpent så lagrer man begge to 
Dermed hoppes det tilbake til medlemskap -> evig løkke.
=> Håndtere opprettet løpende og utført vanlig medlemskap

packages/sak-historikk/i18n/nb_NO.json, packages/sak-historikk/src/kodeverk/historikkEndretFeltTypeCodes.tsx, packages/storybook-utils/mocks/alleKodeverk.json
Legger til nytt historikkfelt fra backend.
@pekern kan du se noe av frontendkoden for FodselInfoPanel m/deler som tilsier at gjeldende dødsdato ikke er populert i formen? 
Fra TFP: "... dødsdato på barnet. Det er ikke mulig å se det i "fakta om fødsel" eller i historikkinnslaget." 
Såvidt jeg ser av eksempler så er dødsdato utfylt i readOnly-modus - men litt usikker på hva som er prepopulert hvis man i samme behandling først løser aksjonspunkt med dødsdato og så går tilbake og prøver løse aksjonspunktet på nytt ....
Fra DEV: Sak 352012696 oppfører seg som forventet når man løser aksjonspunkt på nytt. Datoer er fylt ut. Bruker den til testing
=> TFP-4975 historikk for avklart dødsdato

apps/fp-frontend-app/i18n/nb_NO.json, apps/fp-frontend-app/src/behandling/engangsstonad/prosessPaneler/inngangsvilkarPaneler/AdopsjonInngangsvilkarInitPanel.tsx, apps/fp-frontend-app/src/behandling/engangsstonad/prosessPaneler/inngangsvilkarPaneler/FodselInngangsvilkarInitPanel.tsx, apps/fp-frontend-app/src/behandling/engangsstonad/prosessPaneler/inngangsvilkarPaneler/OmsorgInngangsvilkarInitPanel.tsx, apps/fp-frontend-app/src/behandling/fellesPaneler/prosess/inngangsvilkarPaneler/ForeldreansvarInngangsvilkarInitPanel.tsx, apps/fp-frontend-app/src/behandling/foreldrepenger/prosessPaneler/inngangsvilkarPaneler/AdopsjonInngangsvilkarFpInitPanel.tsx, apps/fp-frontend-app/src/behandling/foreldrepenger/prosessPaneler/inngangsvilkarPaneler/FodselInngangsvilkarFpInitPanel.tsx, apps/fp-frontend-app/src/behandling/foreldrepenger/prosessPaneler/inngangsvilkarPaneler/OmsorgInngangsvilkarFpInitPanel.tsx
Aksjonspunkt 5031 om brukers ytelse gjelder samme barn brukes for ES og FP - oppstår dersom det er søkt på både ES og FP.
Aksjonspunkt 5032 (annen forelders ytelse gjelder samme barn) oppstår kun for ES
Det er brukt samme tekst for begge aksjonspunktene i 4 varianter av SøkersRelasjonTilBarnet-Vilkår-panel. 
Saksbehandlere har reagert og tilpasser derfor tekstene med rammeverk fra OmsorgVilkårpanelet
=> Forskjellig tekst for aksjonspunkt 5031 og 5032

packages/los-avdelingsleder/i18n/nb_NO.json, packages/los-avdelingsleder/src/AvdelingslederIndex.stories.tsx, packages/los-avdelingsleder/src/data/fplosRestApi.tsx, packages/los-avdelingsleder/src/nokkeltall/NokkeltallIndex.tsx, packages/los-avdelingsleder/src/nokkeltall/components/NokkeltallPanel.tsx, packages/los-avdelingsleder/src/nokkeltall/components/ventefristUtløper/VentefristUtløperGraf.tsx, packages/los-avdelingsleder/src/nokkeltall/components/ventefristUtløper/VentefristUtløperPanel.spec.tsx, packages/los-avdelingsleder/src/nokkeltall/components/ventefristUtløper/VentefristUtløperPanel.stories.tsx, packages/los-avdelingsleder/src/nokkeltall/components/ventefristUtløper/VentefristUtløperPanel.tsx
LOS / Avd.leder / Nøkkeltall: Erstatning for graf over manuelt på vent.
Henter og viser liste av enhet, ytelse, behandlingFrist (=autopunkt.frist_tid) og antall (samme innhold som den som erstattes)
Lista hentes fra fpsak (caches 30 min i LOS) og går fra dagens dato og et halvt år fram.
Det kommer sikkert ønske om et kulere ReactEChart etterhvert
=> TFP-5589 erstatning for ventegraf - alle førstegang på vent fordelt på frist

packages/fakta-omsorg-og-rett/src/components/forms/AleneomsorgForm.tsx, packages/fakta-omsorg-og-rett/src/components/forms/HarAnnenForelderRettFelter.tsx, packages/fakta-omsorg-og-rett/src/components/forms/HarAnnenForelderRettForm.tsx
Det er 2 aksjonspunkter med hver sin start-form aleneomsorg og annenForelderRett.
Aleneomsorg mappet ikke inn avklaring av annenForelderEØS - gjør det likt for begge forms og konsekvent med harAnnenForelderRett
=> Mappe ned EØS-verdier også for aleneomsorg

apps/fp-frontend-app/src/behandlingsupport/melding/MeldingIndex.spec.tsx, apps/fp-frontend-app/src/data/behandlingContextApi.ts, apps/fp-frontend-app/src/data/fagsakContextApi.ts, apps/fp-frontend-app/src/data/useVisForhandsvisningAvMelding.tsx
@tor-nav jeg er usikker hvorfor det ikke virker om jeg gjør det likt som i fagsakContext
.withPost('/fpsak/api/brev/forhandsvis/manuell', BehandlingApiKeys.PREVIEW_MESSAGE, { isResponseBlob: true }) -- virker
//.withRel('brev-vis', BehandlingApiKeys.PREVIEW_MESSAGE, { isResponseBlob: true }) --virker ikke 
Men det virker helt ok for de generelle brev fra Meldinger menu.
=> TFP-5668: Flytter forhåndsvisning av brev til å gå gjennom fpsak.

packages/prosess-felles/src/ProsessStegBegrunnelseTextFieldNew.tsx, packages/prosess-formkrav/src/components/FormkravKlageFormNfp.tsx, packages/prosess-klagevurdering/src/components/nfp/FritekstKlageBrevTextField.tsx, packages/prosess-vedtak/src/components/felles/ManueltVedtaksbrevPanel.tsx
Denne skal i teorien virke - i følge en chat med Andreas. Eksempler er "‐ , ‑ , ‒, – , —"
=> Skriv om alle unicode hyphens til minus

packages/fakta-inntektsmelding/i18n/nb_NO.json, packages/fakta-inntektsmelding/src/InntektsmeldingInnhold.tsx, packages/types/src/arbeidOgInntektsmeldingTsType.ts
Har til nå hatt en litt hacky måte å vise frem naturalytelser på. Jeg misforstod da jeg skrev backend, slik at det som kommer som "bortfalteNaturalytelser" er faktisk perioder der den er aktiv. Så trengte å invertere denne logikken
=> Fiks naturalytelser im panel

packages/papirsoknad-ui-komponenter/src/fodselPanel/FodselPapirsoknadIndex.spec.tsx, packages/papirsoknad-ui-komponenter/src/fodselPanel/components/TerminFodselDatoPanel.tsx
Vil dette funke? Har prøvd å isolere Alert til foreldrepenger
Fjerner utstedtdato for tilfelle fødsel - det blir ikke brukt backend - se XSD og subklasser til SoekersRelasjonTilBarnet.
Se storybook /fp-papirsoknad og forskjellen på papirsoknad-es (grid) og papirsoknad-fp (liste av bokser)
=> TFP-5867 be om termindato dersom ES

apps/fp-frontend-app/i18n/nb_NO.json, apps/fp-frontend-app/src/behandlingsupport/BehandlingSupportIndex.spec.tsx, apps/fp-frontend-app/src/behandlingsupport/BehandlingSupportIndex.tsx, packages/sak-historikk-v2/i18n/nb_NO.json
Legger til at vi bare viser det nye. Opprydding av det gammelt historikkinslag og hodeverk kan vi gjøre etterhvert, i en ny PR.
=> TFP-5554: Historikkinnslag baserer seg på ny DTO

packages/papirsoknad-ui-komponenter/i18n/nb_NO.json, packages/papirsoknad-ui-komponenter/src/permisjonFp/components/PermisjonPanel.tsx, packages/papirsoknad-ui-komponenter/src/tilretteleggingSvp/BehovForTilretteleggingPanel.spec.tsx, packages/papirsoknad-ui-komponenter/src/tilretteleggingSvp/BehovForTilretteleggingPanel.tsx, packages/papirsoknad-ui-komponenter/src/tilretteleggingSvp/components/BehovForTilretteleggingFieldArray.tsx, packages/papirsoknad-ui-komponenter/src/tilretteleggingSvp/components/RegistrerArbeidgiverRad.tsx, packages/papirsoknad-ui-komponenter/src/tilretteleggingSvp/components/TilretteleggingForArbeidsgiverFieldArray.tsx, packages/papirsoknad-ui-komponenter/src/tilretteleggingSvp/constants.ts, packages/papirsoknad-ui-komponenter/src/tilretteleggingSvp/types.ts, packages/papirsoknad-ui-komponenter/src/virksomhetPanel/VirksomhetPapirsoknadIndex.spec.tsx, packages/papirsoknad-ui-komponenter/src/virksomhetPanel/components/RegistrerVirksomhetPanel.tsx, packages/papirsoknad-ui-komponenter/src/virksomhetPanel/components/VirksomhetRad.tsx
papirsoknaden inneholdt inputfelter som hadde betinget visning, det gjorde at form felter som ble skjult ved bruk av `<Table.ExpandableRow>` gjorde at feltene ble uregistrer da react hook form ikke lenger fant dem i DOMen.
=> fiks feil i skjult formlogikk i papirsoknad

apps/fp-frontend-app/i18n/nb_NO.json, apps/fp-frontend-app/src/behandling/tilbakekreving/modaler/ÅpenRevurderingModal.spec.tsx, apps/fp-frontend-app/src/behandling/tilbakekreving/modaler/ÅpenRevurderingModal.stories.tsx, apps/fp-frontend-app/src/behandling/tilbakekreving/modaler/ÅpenRevurderingModal.tsx, apps/fp-frontend-app/src/behandling/tilbakekreving/prosessPaneler/VedtakTilbakekrevingProsessInitPanel.tsx
WarningModal er kun brukt et sted i fp-frontend. Den kan med fordel fjernes fra `ft-frontend-saksbehandling` for å minimere vedlikeholdskosten av `ft-frontend-saksbehandling`.
Relatert PR i ft-frontend-saksbehandling: https://github.com/navikt/ft-frontend-saksbehandling/pull/3517
**Før**:
**Etter:**
=> erstatt ft-ui-komponent > WarningModal med aksel sin Modal

packages/fakta-uttaksdokumentasjon/src/components/UttakDokumentasjonFaktaTable/uttakDokumentasjonFaktaTable.module.css
Har endra på margin. Gammal versjon: https://navikt.github.io/fp-frontend/@navikt/fp-fakta-uttaksdokumentasjon/index.html?path=/story/fakta-fakta-uttaksdokumentasjon--aksjonspunkt-med-uavklarte-perioder
Ny versjon:
@sirimykland Har fiksa dette eit par andre stader. Veit du om fleire?
=> FIX margin i uttaksdok (etter at Aksel har endra på tabell-komp)

apps/fp-frontend-app/src/behandling/anke/prosessPaneler/AnkeBehandlingProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/engangsstonad/prosessPaneler/BeregningEsProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/engangsstonad/prosessPaneler/SoknadsfristEsProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/engangsstonad/prosessPaneler/VedtakEsProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/felles/prosess/ProsessDefaultInitPanel.tsx, apps/fp-frontend-app/src/behandling/fellesPaneler/fakta/AdopsjonsvilkaretFaktaInitPanel.tsx, apps/fp-frontend-app/src/behandling/fellesPaneler/fakta/FodselvilkaretFaktaInitPanel.tsx, apps/fp-frontend-app/src/behandling/fellesPaneler/fakta/OmsorgOgForeldreansvarFaktaInitPanel.tsx, apps/fp-frontend-app/src/behandling/fellesPaneler/fakta/OpptjeningsvilkaretFaktaInitPanel.tsx, apps/fp-frontend-app/src/behandling/fellesPaneler/prosess/SimuleringProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/fellesPaneler/prosess/VarselProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/foreldrepenger/prosessPaneler/TilkjentYtelseFpProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/foreldrepenger/prosessPaneler/UttakProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/foreldrepenger/prosessPaneler/VedtakFpProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/foreldrepenger/prosessPaneler/inngangsvilkarPaneler/OpptjeningInngangsvilkarFpInitPanel.tsx, apps/fp-frontend-app/src/behandling/innsyn/prosessPaneler/InnsynVedtakProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/klage/prosessPaneler/KlageresultatProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/svangerskapspenger/prosessPaneler/TilkjentYtelseProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/svangerskapspenger/prosessPaneler/VedtakSvpProsessStegInitPanel.tsx, apps/fp-frontend-app/src/behandling/svangerskapspenger/prosessPaneler/inngangsvilkarPaneler/OpptjeningInngangsvilkarInitPanel.tsx, apps/fp-frontend-app/src/behandling/tilbakekreving/prosessPaneler/ForeldelseProsessInitPanel.tsx, apps/fp-frontend-app/src/behandling/tilbakekreving/prosessPaneler/TilbakekrevingProsessInitPanel.tsx, apps/fp-frontend-app/src/behandling/tilbakekreving/prosessPaneler/VedtakTilbakekrevingProsessInitPanel.tsx, apps/fp-frontend-app/src/data/behandlingApi.ts
Etter endringa av måten rest-kall blir gjort på, tilbake i januar, så er det nokre unødvendig kall som blir gjort. Dvs. data blir korkje brukt til å utleda om panel skal visast, eller i visning av panel. Eg gjekk først gjennom og tilpassa for alt, men etter å ha testa ein del saker via autotest så ser det ut som det i all hovudsak er tre kall som av og til ikkje bør kallast: opptjening, familiehendelse/v2 og feriepengegrunnlag. Så derfor har eg kun tilpassa desse. 
Ein kunne i staden gjort tilpasninga backend, ved å ikkje senda med lenkene. Men eg trur det får komme i ein større oppryddingsjobb etter at me har tenkt litt meir rundt korleis grensenittet bør sjå ut.
=> Ikkje gjer unødvendige kall til backend

apps/fp-frontend-app/src/app/ErrorBoundary.tsx, apps/fp-frontend-app/src/main.tsx
Fjerna funksjonalitet for å legga til ekstra info på api-kall som feilar, fordi ein traff aldri denne koden uansett. Det er kun i ErrorBoundary ein rapporterar feil til sentry per i dag. Mogleg me burde lagt det til i api-feilhåndteringa òg, men so lite som me brukar Sentry per no så ser eg ikkje heilt behovet.
=> Fjern ubrukt funksjonalitet og ikkje bruk sentry lokalt

apps/fp-frontend-app/src/aktoer/AktørIndex.stories.tsx, apps/fp-frontend-app/src/app/AppIndex.stories.tsx, apps/fp-frontend-app/src/app/components/Home.stories.tsx, apps/fp-frontend-app/src/behandling/felles/modaler/paVent/BehandlingPaVent.stories.tsx, apps/fp-frontend-app/src/behandlingmenu/BehandlingMenuIndex.stories.tsx, apps/fp-frontend-app/src/behandlingsupport/BehandlingSupportIndex.stories.tsx, apps/fp-frontend-app/src/behandlingsupport/dokument/DokumentIndex.stories.tsx, apps/fp-frontend-app/src/behandlingsupport/historikk/HistorikkIndex.stories.tsx, apps/fp-frontend-app/src/behandlingsupport/melding/MeldingIndex.stories.tsx, apps/fp-frontend-app/src/behandlingsupport/totrinnskontroll/TotrinnskontrollIndex.stories.tsx, apps/fp-frontend-app/src/data/behandlingApi.ts, apps/fp-frontend-app/src/data/fagsakApi.ts, apps/fp-frontend-app/src/fagsak/FagsakIndex.stories.tsx, apps/fp-frontend-app/src/fagsakSearch/FagsakSearchIndex.stories.tsx, apps/fp-frontend-app/src/fagsakprofile/FagsakProfileIndex.stories.tsx, apps/fp-frontend-app/src/fagsakprofile/risikoklassifisering/RisikoklassifiseringIndex.stories.tsx, packages/journalforing/src/data/fpFordelApi.ts, packages/los/avdelingsleder/src/data/fplosAvdelingslederApi.ts, packages/los/saksbehandler/src/SaksbehandlerIndex.stories.tsx, packages/los/saksbehandler/src/behandlingskoer/oppgaveTabell/OppgaverTabell.spec.tsx, packages/los/saksbehandler/src/behandlingskoer/oppgaveTabell/OppgaverTabell.stories.tsx, packages/los/saksbehandler/src/data/fplosSaksbehandlerApi.ts
* `cleanUrl` fjerner search params fra en lenke. for å fjerne warning output fra tester
* `lagt til https i test urler pga. feil i storybook på github pages:
```
Mixed Content: The page at 'https://navikt.github.io/fp-frontend/@navikt/fp-frontend-app/index.html?path=/story/appindex--default' was loaded over HTTPS, but requested an insecure resource 'http://www.test.com/api/result'. This request has been blocked; the content must be served over HTTPS.
```
=> fjern msw warning om searchparam i requestHandler path

packages/fakta/felles/src/components/FaktaBox.tsx
Løser problem med at flexgrow kun skalerer i forhold til grunnstørrelsen til elementet.  `flexBasis:0%` gjør at den initielle størrelsen er 0 før flex grow gjør at den vokser.
På bilde under ser man at de to boksene på første rad ikke er nøyaktig 50/50 slik de skal være.
jeg la også til aria label for at vi kan bruke den til testing
=> fiks flexgrow på FaktaBox slik at det blir lik bredde på hvert element

packages/prosess/formkrav/i18n/nb_NO.json, packages/prosess/formkrav/src/FormkravProsessIndex.spec.tsx, packages/prosess/formkrav/src/FormkravProsessIndex.stories.tsx, packages/prosess/formkrav/src/components/FormkravKlageFormNfp.tsx, packages/prosess/formkrav/src/components/TempsaveKlageButton.tsx, packages/prosess/formkrav/src/types/FormkravMellomlagretDataType.ts, packages/types-avklar-aksjonspunkter/src/prosess/KlageFormkravAp.ts, packages/types/src/klageVurderingTsType.ts
Jeg måtte legge mottattDato på toppnivå i Dto fra backend.
Dermed ble det litt knot for å kun sette denne mens andre form-values er undefined.
Det finnes sikkert en bedre måte å strukturere dette på - fx setValue.
Obs: Det var allerede en erTilbakekreving?: boolean i KlageFormkravBasic
=> TFP-1059 utkast klage mottatt dato

packages/papirsoknad-ui-komponenter/i18n/nb_NO.json, packages/papirsoknad-ui-komponenter/src/omsorgOgAdopsjonPanel/OmsorgOgAdopsjonPapirsoknadIndex.spec.tsx, packages/papirsoknad-ui-komponenter/src/omsorgOgAdopsjonPanel/components/OmsorgOgAdopsjonPanel.tsx
Ankomstdato trengs ikke lenger.  Det så ikke ut som ankomstdato ble mappet til det som lagres til backend.
=> TFP-6401 fjerne ankomstdato fra papirsøknad
