- .github/workflows/build-and-deploy-master.yml
- nais/dev-fss-q0.json
- nais/dev-fss-t4.json
- nais/dev-fss-teamforeldrepenger.json
- nais/prod-fss-teamforeldrepenger.json
La til teamforeldrepenger og fjernet t4 + q0
Frontend bruker service-discovery i ns - "http://fpsak/" - så vi må vente med deploy til teamforeldrepenger til vi har fpsak ute 
Tror overgangen bør gå greit men fint om noen (finner noen) til å jobbe litt med nginx
> NOJIRA fjerner t4 legger til teamforeldrepenger

- packages/fakta-arbeidsforhold/src/components/PersonArbeidsforholdPanel.jsx
- packages/fakta-arbeidsforhold/src/components/PersonArbeidsforholdPanel.spec.jsx
Signed-off-by: Ole Jørgen Rishoff <olejri@gmail.com>
> TFP-3682 sjekker nå valgt arbeidsforhold

- packages/prosess-anke-trygderettsbehandling/src/components/TrygderettsbehandlingForm.tsx
Flyttet resultat Trygderetten under fritekstfeltet, men over Lagre-knapp
> TFP-4077 trygderettsresultat under fritekst

- packages/fakta-fodsel/src/components/TermindatoFaktaForm.tsx
Vilkåret lar den passere hvis utstedt >= termin-18u3d
Frontend sjekket at utstedt > termin-18u3d - trekker fra ekstra dag for å få >=
> TFP-4336 utstedt skal være fom termin-18u-3d

- packages/storybook/stories/fakta/MedlemskapFaktaIndex.stories.tsx
- packages/storybook/stories/fakta/mocks/uttak/far-soker-forste-seks-uker/personopplysninger.json
- packages/storybook/stories/fakta/mocks/uttak/overforing-av-perioder/personopplysninger.json
- packages/storybook/stories/fakta/mocks/uttak/vurder-annen-part-har-rett/personopplysninger.json
- packages/types/src/personadresseTsType.ts
Fant ikke noe bruk av mottakernavn i personAdresseType.ts - fjerner den front og backend
@tor-nav  ser du noe jeg har glemt/oversett ?
> Fjerne ubrukt felt mottakernavn fra personadresse

- packages/sak-historikk/i18n/nb_NO.json
- packages/sak-historikk/src/kodeverk/historikkEndretFeltTypeCodes.tsx
- packages/storybook-utils/mocks/alleKodeverk.json
Tekst dersom saksbehandler har avklart om mor mottar uføretrygd eller ei - oppstår ifm aksjonspunkt på annen part rett
Felt er Boolean Ja / Nei så ikke noe ekstra der
Mangler jeg noe?
> TFP-4678 BareFarRett MorUføre historikkinnslag

- packages/behandling-anke/src/prosessPaneler/AnkeBehandlingProsessStegInitPanel.spec.tsx
- packages/behandling-anke/src/prosessPaneler/AnkeBehandlingProsessStegInitPanel.tsx
- packages/behandling-anke/src/prosessPaneler/AnkeResultatProsessStegInitPanel.spec.tsx
- packages/behandling-anke/src/prosessPaneler/AnkeResultatProsessStegInitPanel.tsx
- packages/behandling-es/src/prosessPaneler/VarselProsessStegInitPanel.spec.tsx
- packages/behandling-es/src/prosessPaneler/VarselProsessStegInitPanel.tsx
- packages/behandling-es/src/prosessPaneler/VedtakProsessStegInitPanel.tsx
- packages/behandling-fp/src/prosessPaneler/VarselProsessStegInitPanel.spec.tsx
- packages/behandling-fp/src/prosessPaneler/VarselProsessStegInitPanel.tsx
- packages/behandling-fp/src/prosessPaneler/VedtakProsessStegInitPanel.tsx
- packages/behandling-innsyn/src/prosessPaneler/InnsynVedtakProsessStegInitPanel.spec.tsx
- packages/behandling-innsyn/src/prosessPaneler/InnsynVedtakProsessStegInitPanel.tsx
- packages/behandling-klage/src/prosessPaneler/KlageresultatProsessStegInitPanel.spec.tsx
- packages/behandling-klage/src/prosessPaneler/KlageresultatProsessStegInitPanel.tsx
- packages/behandling-klage/src/prosessPaneler/VurderingFellesProsessStegInitPanel.spec.tsx
- packages/behandling-klage/src/prosessPaneler/VurderingFellesProsessStegInitPanel.tsx
- packages/behandling-svp/src/prosessPaneler/VedtakProsessStegInitPanel.tsx
- packages/prosess-vedtak/src/VedtakProsessIndex.spec.tsx
- packages/prosess-vedtak/src/components/forstegang/VedtakForm.tsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingForm.tsx
- packages/sak-app/src/behandlingsupport/melding/MeldingIndex.spec.tsx
- packages/sak-app/src/behandlingsupport/melding/MeldingIndex.tsx
- packages/sak-app/src/behandlingsupport/totrinnskontroll/TotrinnskontrollIndex.tsx
- packages/sak-app/src/data/useVisForhandsvisningAvMelding.tsx
- packages/sak-meny-henlegg/src/MenyHenleggIndex.spec.tsx
- packages/sak-meny-henlegg/src/components/HenleggBehandlingModal.tsx
- packages/types/src/forhåndsvisMeldingParamsTsType.ts
Har byttet om i fpformidling, så sanerer gammel ytelsetype og vedtaksbrev
> Modernisere forhåndsvisning

- packages/prosess-formkrav/i18n/nb_NO.json
- packages/prosess-formkrav/src/FormkravProsessIndex.tsx
- packages/prosess-formkrav/src/components/FormkravKlageFormKa.tsx
- packages/types-avklar-aksjonspunkter/src/ProsessAksjonspunkt.ts
- packages/types-avklar-aksjonspunkter/src/prosess/KlageFormkravAp.ts
- packages/types/src/klageVurderingTsType.ts
Valg + Hjemmel + Knappetekst for å sende til KABAL fra Formkrav/KA
> TFP-4903 frontend for å sende klage til Kabal

- packages/fakta-felles/src/utils/isFieldEdited.spec.ts
- packages/fakta-omsorg-og-rett/i18n/nb_NO.json
- packages/fakta-omsorg-og-rett/src/components/forms/AleneomsorgForm.tsx
- packages/fakta-omsorg-og-rett/src/components/forms/HarAnnenForelderRettFelter.tsx
- packages/fakta-omsorg-og-rett/src/components/forms/HarAnnenForelderRettForm.tsx
- packages/fakta-omsorg/src/OmsorgFaktaIndex.stories.tsx
- packages/fakta-uttak/src/UttakFaktaindex.stories.tsx
- packages/fakta-uttak/testdata/far-soker-forste-seks-uker/ytelsefordeling.json
- packages/fakta-uttak/testdata/overforing-av-perioder/ytelsefordeling.json
- packages/prosess-uttak/src/UttakProsessIndex.stories.tsx
- packages/prosess-uttak/src/components/UttakPanel.spec.tsx
- packages/sak-historikk/i18n/nb_NO.json
- packages/sak-historikk/src/kodeverk/historikkEndretFeltTypeCodes.tsx
- packages/storybook-utils/mocks/alleKodeverk.json
- packages/types-avklar-aksjonspunkter/src/fakta/AvklarAnnenforelderHarRettAp.ts
- packages/types-avklar-aksjonspunkter/src/fakta/BekreftAleneomsorgVurderingAp.ts
- packages/types/src/soknadTsType.ts
- packages/types/src/ytelsefordelingTsType.ts
Legger til avklaring av om mor har foreldrepenger fra eøs for aleneomsorg+annenforelderrett
Forenkler soknadTsType og ytelseForedelingTsType - omlegging av datastruktur og fjerne ubrukte felt
> TFP-5014 legg til avklaring mor fp eøs for omsorgrett

- packages/fakta-omsorg-og-rett/i18n/nb_NO.json
- packages/fakta-omsorg-og-rett/src/OmsorgOgRettFaktaIndex.spec.tsx
- packages/fakta-omsorg-og-rett/src/components/forms/AleneomsorgForm.tsx
- packages/fakta-omsorg-og-rett/src/components/forms/HarAnnenForelderRettFelter.tsx
- packages/fakta-omsorg-og-rett/src/components/forms/HarAnnenForelderRettForm.tsx
- packages/fakta-uttak/src/UttakFaktaindex.stories.tsx
- packages/fakta-uttak/testdata/far-soker-forste-seks-uker/ytelsefordeling.json
- packages/fakta-uttak/testdata/overforing-av-perioder/ytelsefordeling.json
- packages/papirsoknad-ui-komponenter/i18n/nb_NO.json
- packages/papirsoknad-ui-komponenter/src/permisjonFp/components/PermisjonRettigheterPanel.tsx
- packages/prosess-uttak/src/UttakProsessIndex.stories.tsx
- packages/sak-historikk/i18n/nb_NO.json
- packages/sak-historikk/src/kodeverk/historikkEndretFeltTypeCodes.tsx
- packages/storybook-utils/mocks/alleKodeverk.json
- packages/types-avklar-aksjonspunkter/src/fakta/AvklarAnnenforelderHarRettAp.ts
- packages/types-avklar-aksjonspunkter/src/fakta/BekreftAleneomsorgVurderingAp.ts
- packages/types/src/ytelsefordelingTsType.ts
En del renaming + annen rekkefølge av spørsmål i et par panel. Annen part rett EØS -> opprett kvoter.
Merges etter tilsvarende PR i fpsak
> TFP-5159 ny modell for avklaring av rett og eøs

- packages/prosess-anke-trygderettsbehandling/i18n/nb_NO.json
- packages/prosess-anke-trygderettsbehandling/src/AnkeTrygderettsbehandlingProsessIndex.stories.tsx
- packages/prosess-anke-trygderettsbehandling/src/AnkeTrygderettsbehandlingProsessIndex.tsx
- packages/prosess-anke-trygderettsbehandling/src/components/TrygderettsbehandlingForm.spec.tsx
- packages/prosess-anke-trygderettsbehandling/src/components/TrygderettsbehandlingForm.tsx
- packages/sak-app/src/behandling/anke/BehandlingAnkeIndex.tsx
- packages/sak-app/src/behandling/anke/prosessPaneler/AnkeTrygderettsbehandlingProsessStegInitPanel.tsx
- packages/types-avklar-aksjonspunkter/src/prosess/AnkeMerknaderResultatAp.ts
- packages/types/src/ankeVurderingTsType.ts
Siste steg før migering av siste 115 anker til Kabal. Deretter sanering
> TFP-5159 funksjonalitet for å sende tr-anker til Kabal

- packages/kodeverk/src/behandlingResultatType.ts
- packages/sak-app/src/behandling/BehandlingIndex.tsx
- packages/sak-app/src/behandling/klage/prosessPaneler/FormKravKlageInstansProsessStegInitPanel.tsx
Er dette en rimelig måte å løse ting på?
> Klage på avvisning av klage

- packages/sak-app/src/behandling/klage/prosessPaneler/FormKravFamOgPensjonProsessStegInitPanel.tsx
Få inn filteret i riktig prosess-panel. Forrige pr tok det inn i FormkravKA - som jo er usynlig ....
> TFP-5283 tillat klage på avvist klage nfp formkrav

- @types/module-federation-remotes.d.ts
- packages/sak-app/package.json
- packages/sak-app/src/behandling/forstegangsoknadOgRevurdering/paneler/fakta/BeregningFaktaInitPanel.tsx
- yarn.lock
This reverts commit 7e8f1ef5602354082a77fee3d1b12d0644e746b0.
> Revert "Tar i bruk fakta om beregning som pakke (#3773)"

- @types/module-federation-remotes.d.ts
- packages/sak-app/package.json
- packages/sak-app/src/behandling/forstegangsoknadOgRevurdering/paneler/fakta/BeregningFaktaInitPanel.tsx
- yarn.lock
This reverts commit 014b81cdf60dc3c8970556118cf3390e1e58911d.
> Tar i bruk fakta om beregning som pakke

- server/src/main.js
- server/src/reverse-proxy.js
Fikser proxy error hvis fplos er utilgjengelig også.
> Setter riktig referrer-policy til origin

- packages/fakta-omsorg/src/OmsorgFaktaIndex.spec.tsx
- packages/fakta-omsorg/src/components/OmsorgFaktaForm.tsx
- packages/fakta-uttak-legacy/src/UttakFaktaindex.stories.tsx
- packages/fakta-uttak/src/UttakFaktaIndex.stories.tsx
- packages/types/src/ytelsefordelingTsType.ts
Nytt felt overstyrtOmsorg - boolean som skal erstatte konvensjonen med perioder.
Neste steg blir å legge om til kun Ja/Nei og helt fjerne periode-valg dersom man velger fra omsorg-panelet
> TFP-5036 forberedelse til omlegging av omsorgsap

- apps/fp-frontend-app/src/behandling/felles/data/behandlingFellesApi.ts
- apps/fp-frontend-app/src/behandling/forstegangsoknadOgRevurdering/paneler/fakta/OpptjeningsvilkaretFaktaInitPanel.tsx
- apps/fp-frontend-app/src/behandling/forstegangsoknadOgRevurdering/paneler/fakta/SakenFaktaInitPanel.tsx
- packages/fakta-opptjening/src/OpptjeningFaktaIndex.tsx
- packages/fakta-opptjening/src/components/OpptjeningFaktaPanel.tsx
- packages/fakta-saken/src/SakenFaktaIndex.tsx
- packages/fakta-saken/src/components/SakenFaktaPanel.tsx
- packages/fakta-saken/src/components/utland/UtlandPanel.tsx
- packages/kodeverk/index.ts
- packages/kodeverk/src/utlandMarkeringKode.tsx
- packages/types/src/fagsakTsType.ts
Fjerner dokument-innhetet-kommentar fra opptjeningspanel etter avtale med Marte
Gjør dokstatus nullable og legger til nytt felt utlandMarkering som etterhvert er prepopulert
> TFP-5427 initiell tilpasning til ny utlandmarkering

- apps/fp-frontend-app/package.json
- apps/fp-frontend-app/src/fagsakprofile/FagsakProfileIndex.tsx
- yarn.lock
Virker denne OK? Gitt at fagsak.utlandMarkering kan være undefined / null
Bær vi oppdatere alle versjon 2.0.4 til 2.0.6 ? Evt et subset?
> Legg til utland-markering

- apps/fp-frontend-app/package.json
- apps/fp-frontend-app/src/app/AppIndex.tsx
- apps/fp-frontend-app/src/behandlingmenu/BehandlingMenuIndex.tsx
- apps/fp-frontend-app/src/data/fpsakApi.ts
- packages/sak-meny-endre-utland/.storybook/main.cjs
- packages/sak-meny-endre-utland/.storybook/manager.js
- packages/sak-meny-endre-utland/.storybook/preview.jsx
- packages/sak-meny-endre-utland/i18n/nb_NO.json
- packages/sak-meny-endre-utland/index.ts
- packages/sak-meny-endre-utland/package.json
- packages/sak-meny-endre-utland/src/MenyEndreUtlandIndex.spec.tsx
- packages/sak-meny-endre-utland/src/MenyEndreUtlandIndex.stories.tsx
- packages/sak-meny-endre-utland/src/MenyEndreUtlandIndex.tsx
- packages/sak-meny-endre-utland/src/components/EndreUtlandModal.tsx
- packages/sak-meny-endre-utland/src/components/endreUtlandModal.module.css
- packages/sak-meny-endre-utland/tsconfig.json
- packages/sak-meny-endre-utland/vite.config.js
- yarn.lock
Første grovutkast. Litt plunder med å kjøre lokalt.
> TFP-5427 endre utland i behandlingmeny

- apps/fp-frontend-app/src/behandlingmenu/BehandlingMenuIndex.tsx
- apps/fp-frontend-app/src/data/fpsakApi.ts
- apps/fp-frontend-app/src/fagsakprofile/FagsakProfileIndex.tsx
- packages/kodeverk/index.ts
- packages/kodeverk/src/fagsakMarkeringKode.tsx
- packages/kodeverk/src/utlandMarkeringKode.tsx
- packages/sak-meny-endre-utland/i18n/nb_NO.json
- packages/sak-meny-endre-utland/src/MenyEndreUtlandIndex.spec.tsx
- packages/sak-meny-endre-utland/src/MenyEndreUtlandIndex.stories.tsx
- packages/sak-meny-endre-utland/src/MenyEndreUtlandIndex.tsx
- packages/sak-meny-endre-utland/src/components/EndreUtlandModal.tsx
- packages/types/src/fagsakTsType.ts
Kommer en runde til med oppdatert ft-frontend
> TFP-5457 flere valg for saksmerking

- apps/fp-frontend-app/src/fagsakprofile/FagsakProfileIndex.tsx
- packages/kodeverk/src/fagsakMarkeringKode.tsx
- packages/sak-historikk/i18n/nb_NO.json
- packages/sak-historikk/src/kodeverk/historikkEndretFeltVerdiTypeCodes.tsx
- packages/sak-meny-endre-utland/i18n/nb_NO.json
- packages/sak-meny-endre-utland/src/components/EndreUtlandModal.tsx
Støtte for fagsaksmarkering av død og dødfødsel
> TFP-1846 egenskaper for dødstilfelle og næring

- apps/fp-frontend-app/src/app/components/Dekorator.tsx
Avklart med Marte - lanseres i dag for alle.
> TFP-4124 - vis journalføring lenke i meny.

- apps/fp-frontend-app/src/behandlingmenu/modaler/NyBehandlingMenyModal.tsx
- packages/sak-meny-ny-behandling/i18n/nb_NO.json
- packages/sak-meny-ny-behandling/src/MenyNyBehandlingIndex.spec.tsx
- packages/sak-meny-ny-behandling/src/MenyNyBehandlingIndex.stories.tsx
- packages/sak-meny-ny-behandling/src/components/NyBehandlingModal.tsx
Fjerner anke som mulighet, ellers blir den stående som ikke enabled
> TFP-5566 Fjerne anke fra opprett-behandling-modal-liste

- packages/los-avdelingsleder/i18n/nb_NO.json
- packages/los-avdelingsleder/src/AvdelingslederIndex.tsx
- packages/los-avdelingsleder/src/nokkeltall/components/antallBehandlingerPerForsteStonadsdag/OppgaverPerForsteStonadsdagPanel.spec.tsx
- packages/los-avdelingsleder/src/nokkeltall/components/apneOgPaVentBehandlinger/OppgaverSomErApneEllerPaVentPanel.spec.tsx
- packages/los-avdelingsleder/src/nokkeltall/components/fordelingAvBehandlingstype/FordelingAvBehandlingstypePanel.spec.tsx
- packages/los-avdelingsleder/src/nokkeltall/components/tilBehandling/TilBehandlingPanel.spec.tsx
> Bedre veiledningstekster nøkkeltall

- packages/prosess-varsel-om-revurdering/src/components/VarselOmRevurderingForm.tsx
- packages/prosess-vedtak/src/components/felles/ManueltVedtaksbrevPanel.tsx
- packages/sak-meldinger/src/components/Messages.tsx
For å gjøre avanserte tilfelle fornøyd
> TFP-5548 uvide maxlengde vedtaksbrev til 10000

- packages/prosess-tilkjent-ytelse/src/TilkjentYtelseProsessIndex.stories.tsx
- packages/types/src/feriepengegrunnlagTsType.ts
Fjerner 4 stk fom/tom som ikke er i bruk i panelene.
> Fjerne ubrukte felt i feriepengerDto

- packages/fakta-uttak/src/components/UttakFaktaDetailForm.tsx
- packages/kodeverk/src/uttakPeriodeType.ts
- packages/prosess-uttak/i18n/nb_NO.json
- packages/prosess-uttak/src/UttakProsessIndex.stories.tsx
- packages/prosess-uttak/src/components/tidslinje/UttakTidslinje.tsx
> Fjerner ubrukt ANNET uttakperiodetype

- packages/prosess-simulering/src/components/TilbakekrevSøkerForm.tsx
- packages/prosess-varsel-om-revurdering/src/components/VarselOmRevurderingForm.tsx
- packages/prosess-vedtak-innsyn/src/components/InnsynVedtakForm.tsx
- packages/prosess-vedtak/src/components/felles/VedtakFritekstPanel.tsx
- packages/prosess-vedtak/src/components/revurdering/VedtakAvslagArsakOgBegrunnelsePanel.tsx
- packages/sak-meldinger/src/components/Messages.tsx
- packages/sak-meny-henlegg/src/components/HenleggBehandlingModal.tsx
Lå allerede inne for vedtaksbrev. Legger på for andre brev (varsel + messages ++) og felter der man tar inn tekst som skal inn som avsnitt
> Skriv om hyphens i flere brev-felter

- packages/los-avdelingsleder/src/grupper/components/GruppeSaksbehandlere.tsx
- packages/los-avdelingsleder/src/grupper/components/GrupperPanel.spec.tsx
Implementerer en filterfunksjon som matcher substringer uavhengig av startposisjon.
> Smartere autocomplete

- packages/sak-meny-endre-utland/src/components/EndreUtlandModal.tsx
Ting ser bra ut, men vil ikke kreve at noen boxes er checked
> Endre saksmerking - tillat at ingen velges

- packages/prosess-simulering/src/components/SimuleringTable.tsx
This reverts commit 4922210c4c70ab393d703089734b395100aa2022.
> Revert "FIX: Viser ikke ugyldige datoer (#5698)"

- apps/fp-frontend-app/index.html
- apps/fp-frontend-app/package.json
- apps/fp-frontend-app/src/main.tsx
> Rename for å matche med vite mode

- packages/fakta-inntektsmelding/src/InntektsmeldingInnhold.tsx
Denne skulle ikke vært commited
> Fjern tekst i inntektsmeldingInnhold for behandling som ikke skal være med

- apps/fp-frontend-app/i18n/nb_NO.json
- packages/fakta-inntektsmelding/i18n/nb_NO.json
- packages/fakta-inntektsmelding/src/InntektsmeldingFaktaIndex.spec.tsx
- packages/fakta-inntektsmelding/src/InntektsmeldingFaktaIndex.stories.tsx
- packages/fakta-inntektsmelding/src/InntektsmeldingFaktaIndex.tsx
- packages/fakta-inntektsmelding/src/InntektsmeldingInnhold.tsx
- packages/types/src/arbeidOgInntektsmeldingTsType.ts
justere iht tilbakemelding fra test
> Tilbakemeldinger im panel

- packages/prosess-formkrav/src/components/FormkravKlageFormNfp.tsx
- packages/sak-notat/src/components/NotatPanel.tsx
Disse 2 rakkerne står bak en del del valideringsfeil i loggene. Alle andre TextAreaField har hasValidText.
> Manglende tekstvalidering i 2 TextAreaFields

- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.stories.tsx
- packages/types/index.ts
- packages/types/src/medlemskapV3TsType.ts
https://github.com/navikt/fp-sak/pull/6677
matche backend
> TFP-5732 nye typer medlemskapavvik fra v3 dto

- eslint.config.mjs
- packages/fakta-medlemskap/i18n/nb_NO.json
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.stories.tsx
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.tsx
- packages/fakta-medlemskap/src/v3/MedlemskapInfoPanel.tsx
- packages/fakta-medlemskap/src/v3/components/AksjonspunktHelpText.tsx
- packages/fakta-medlemskap/src/v3/components/situasjon/Situasjon.tsx
- packages/fakta-medlemskap/src/v3/components/situasjon/SituasjonOversikt.tsx
- packages/fakta-medlemskap/src/v3/components/situasjon/situasjonUtils.spec.ts
- packages/fakta-medlemskap/src/v3/components/situasjon/situasjonUtils.ts
- packages/fakta-medlemskap/src/v3/types.ts
> legge til situasjonsoversikt

- packages/fakta-medlemskap/i18n/nb_NO.json
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.spec.tsx
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.stories.tsx
- packages/fakta-medlemskap/src/v3/components/Divider.tsx
- packages/fakta-medlemskap/src/v3/components/MedlemskapInfoPanel.tsx
- packages/fakta-medlemskap/src/v3/components/ekspansjonsKort/EkspansjonsKort.tsx
- packages/fakta-medlemskap/src/v3/components/opplysningsKort/OpplysningerOmPersonstatus/OpplysningerOmPersonstatus.tsx
- packages/fakta-medlemskap/src/v3/components/opplysningsKort/OpplysningerOmPersonstatus/PersonstatusVisning.tsx
- packages/fakta-medlemskap/src/v3/components/opplysningsKort/OpplysningerOmPersonstatus/RegionVisning.tsx
- packages/fakta-medlemskap/src/v3/utils/personstatusUtils.ts
- packages/kodeverk/src/region.ts
- packages/types/index.ts
- packages/types/src/medlemskapV3TsType.ts
> legge til personstatus og statborgerskapspanel

- packages/fakta-medlemskap/i18n/nb_NO.json
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.spec.tsx
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.stories.tsx
- packages/fakta-medlemskap/src/v3/components/MedlemskapInfoPanel.tsx
- packages/fakta-medlemskap/src/v3/components/opplysningsKort/OpplysningerFraMedlemskapsregister.tsx
- packages/fakta-medlemskap/src/v3/utils/landUtils.ts
- packages/types/index.ts
- packages/types/src/medlemskapV3TsType.ts
> legge til opplysninger fra medlemregister i fakta medlemskap

- packages/fakta-medlemskap/i18n/nb_NO.json
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.spec.tsx
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.stories.tsx
- packages/fakta-medlemskap/src/v3/components/MedlemskapInfoPanel.tsx
- packages/fakta-medlemskap/src/v3/components/ekspansjonsKort/EkspansjonsKort.tsx
- packages/fakta-medlemskap/src/v3/components/opplysningsKort/OpplysningerOmOppholdstillatelser.tsx
- packages/types/index.ts
- packages/types/src/medlemskapV3TsType.ts
> legge til seksjon om oppholdstilatelse i fakta medlemskap

- packages/fakta-medlemskap/i18n/nb_NO.json
- packages/fakta-medlemskap/src/v3/MedlemskapFaktaIndex.spec.tsx
> TFP-5732 tekstfix bostedsadresse medlemskap

- packages/fakta-medlemskap/i18n/nb_NO.json
- packages/fakta-medlemskap/src/v3/components/aksjonspunkt/VurderMedlemsskapLegacyAksjonspunktVisning.tsx
med en periode
med flere perioder
> endre legacy view av vurderingsdato i medlemskapspanel

- packages/fakta-medlemskap/src/v3/components/aksjonspunkt/VurderingAlternativer.tsx
- packages/fakta-medlemskap/src/v3/components/aksjonspunkt/VurderingAlternativerForutgaende.tsx
- packages/prosess-felles/src/vilkar/VilkarResultPicker.tsx
Odde og varierende rekkefølge på avslagene - vi ønsker stabile dropdowns.
Evt får backend sortere alle kodeverk på Navn :-)
> Sorter avslagsårsaker på navn

- packages/fakta-medlemskap/src/v3/components/aksjonspunkt/VilkårResultatPickerMedlemskapsvilkåretForutgående.tsx
Må kanskje inn med noe lignende i overstyring?
> viser ikke innflyttingsdato hvis saksbehandler velger oppfylt

- apps/fp-frontend-app/.storybook/testdata/alleInntektsmeldinger.json
- apps/fp-frontend-app/.storybook/testdata/behandlingV1.json
- apps/fp-frontend-app/.storybook/testdata/behandlingV2.json
- apps/fp-frontend-app/.storybook/testdata/fagsakFullRisikoAp.json
- apps/fp-frontend-app/.storybook/testdata/medlemskap.json
- apps/fp-frontend-app/.storybook/testdata/personoversikt.json
- apps/fp-frontend-app/.storybook/testdata/soknad.json
- apps/fp-frontend-app/src/app/AppIndex.stories.tsx
Vi bør nok se på å oppdatere disse storiene med ny data fra dev. Dette er i midlertid nok til å fikse ødelagt stories i `@navikt/fp-frontend-app`
> fiks ødelagte stories

- server/src/reverse-proxy.js
Noe usikker om det gir noe effekt siden vi ikke bruker en body parser middleware.
> Fjerner eksplisitt parsing av body fra proxy

- apps/fp-frontend-app/src/behandlingsupport/melding/MeldingIndex.tsx
- apps/fp-frontend-app/src/behandlingsupport/melding/SettPaVentReadOnlyModal.tsx
Har gjort litt endringer backend slik at man kan sende melding selv om behandling på vent - men uten å røre eksisterende ventefrist.
Håper denne skal vise frist fra behandling dersom finnes, ellers fast frist. Nå er det bare en fast frist som vises.
> TFP-6002 vise frist fra behandling hvis finnes

- apps/fp-frontend-app/src/behandlingmenu/modaler/VergeMenyModal.tsx
> TFP-5957: endre vergemodal til å bytte til ny versjon basert på tilgjengelig relasjonslenke

- packages/fakta/fakta-omsorg-og-rett/src/OmsorgOgRettFaktaIndex.spec.tsx
- packages/fakta/fakta-omsorg-og-rett/src/OmsorgOgRettFaktaIndex.stories.tsx
- packages/fakta/fakta-omsorg-og-rett/src/opplysningskort/AnnenPartsYtelser.tsx
- packages/types/src/omsorgOgRettTsType.ts
> TFP-5965: Utvidet med flere stories for 'omsorg og rett'.

- packages/fakta/arbeidsforhold/i18n/nb_NO.json
- packages/fakta/arbeidsforhold/src/ArbeidsforholdFaktaIndex.spec.tsx
- packages/storybook-utils/mocks/alleKodeverk.json
følger sammen med https://github.com/navikt/fp-sak/pull/7241
> omdøp navn for Aa-reg

- packages/ui-komponenter/src/DokumentLink.tsx
> FAGSYSTEM-377247: fiks duplikat åpning av dokumenter ved bruk av CTRL-tast

- packages/modal-sett-pa-vent/.storybook/preview.tsx
- packages/papirsoknad-ui-komponenter/.storybook/preview.tsx
- packages/papirsoknad/.storybook/preview.tsx
Feil path har gjort at `storybook-build-all`-steget har feilet i workflow Deploy Storybook
> fiks storybook konfig med feil path til preview

- packages/los/saksbehandler/i18n/nb_NO.json
- packages/los/saksbehandler/src/data/fplosSaksbehandlerApi.ts
- packages/los/saksbehandler/src/saksstotte/sistBehandlede/SistBehandledeSaker.tsx
Må ha oppdatert fplos-backend før denne kan merges (se https://github.com/navikt/fplos/pull/2207)
> TFP-6364: innføre kun åpne-toggle for siste-reserverte
